### PR TITLE
Fix for subdirs that doesn't exist at the git repo HEAD

### LINKED ISSUE #28: subdir issue
```julia
julia> analyze_from_registry(find_package("SnoopCompileAnalysis"))
ERROR: IOError: readdir("/var/folders/jb/plyyfc_d2bz195_0rc0n_zcw0000gp/T/jl_jE3Zv2/9ea4277c-da97-4c3a-afb0-537c066769de/SnoopCompileAnalysis"): no such file or directory (ENOENT)
Stacktrace:
  [1] uv_error
    @ ./libuv.jl:97 [inlined]
  [2] readdir(dir::String; join::Bool, sort::Bool)
    @ Base.Filesystem ./file.jl:830
  [3] readdir
    @ ./file.jl:825 [inlined]
  [4] readfiles
    @ ~/.julia/packages/LicenseCheck/OJxVg/src/find_licenses.jl:24 [inlined]
  [5] find_licenses(dir::String; allow_brute::Bool, max_bytes::Int64)
    @ LicenseCheck ~/.julia/packages/LicenseCheck/OJxVg/src/find_licenses.jl:110
  [6] find_licenses
    @ ~/.julia/packages/LicenseCheck/OJxVg/src/find_licenses.jl:110 [inlined]
  [7] analyze(dir::String; repo::String, reachable::Bool, subdir::String)
    @ AnalyzeRegistry ~/.julia/dev/AnalyzeRegistry/src/AnalyzeRegistry.jl:360
  [8] analyze_from_registry!(root::String, dir::String)
    @ AnalyzeRegistry ~/.julia/dev/AnalyzeRegistry/src/AnalyzeRegistry.jl:229
  [9] #42
    @ ~/.julia/dev/AnalyzeRegistry/src/AnalyzeRegistry.jl:277 [inlined]
 [10] mktempdir(fn::AnalyzeRegistry.var"#42#43"{String}, parent::String; prefix::String)
    @ Base.Filesystem ./file.jl:729
 [11] mktempdir
    @ ./file.jl:727 [inlined]
 [12] analyze_from_registry(p::String)
    @ AnalyzeRegistry ~/.julia/dev/AnalyzeRegistry/src/AnalyzeRegistry.jl:276
 [13] top-level scope
    @ REPL[6]:1
```

The problem is that the code for the package was removed in https://github.com/timholy/SnoopCompile.jl/pull/127, so AnalyzeRegistry can't find it from cloning the repo (and it's not `Pkg.dev`'able). It's still `Pkg.add`'able though, so we could get the code that way if we wanted.

### PR DESCRIPTION
**Pull request by ericphanson**
This makes some minimal changes to close #28. We just check that the subdir exists for before looking for licenses / code in it. I also added the `subdir` to the `show` method; I think this is good either way since it's interesting to see it's a subdir package, but is particularly important when we can't parse the Project.toml so we don't have a name, and the repo alone doesn't identify the package, ref https://github.com/giordano/AnalyzeRegistry.jl/issues/28#issuecomment-782979547.

```julia
julia> analyze_from_registry!(root, find_package("SnoopCompileAnalysis"))
Package Invalid Project.toml:
  * repo: https://github.com/timholy/SnoopCompile.jl.git
    * in subdirectory: SnoopCompileAnalysis
  * uuid: 00000000-0000-0000-0000-000000000000
  * is reachable: true
  * no license found
  * has documentation: false
  * has tests: false
  * has continuous integration: true
    * GitHub Actions
```

I think a simple fix like this is OK; as I see it, AnalyzeRegistry has two use cases: analyzing a whole registry, in which case a couple unreachable-at-HEAD packages is somewhat expected and it's not that important to go out of our way to find their code, and for analyzing a particular package, in which case the code probably exists or else you wouldn't be looking at it.

### CODE REVIEW

File: test/runtests.jl [hunk 1]
```diff
@@ -89,6 +89,10 @@ end
     snoop_compile_count_for_core = sum(row.code for row in snoop_compile.lines_of_code if row.language == :Julia && row.sublanguage===nothing && row.directory == "SnoopCompileCore")
     snoop_core_count = sum(row.code for row in snoop_core.lines_of_code if row.language == :Julia && row.sublanguage===nothing)
     @test snoop_core_count == snoop_compile_count_for_core
+
+    # this package doesn't exist in the repo anymore; let's ensure it doesn't throw
+    snoop_compile_analysis = analyze_from_registry(find_package("SnoopCompileAnalysis"))
+    @test isempty(snoop_compile_analysis.lines_of_code)
```
Comment (giordano) [inline test/runtests.jl:95]: Let's hope this won't change in the future :joy:

**Review by giordano — APPROVED** [review]
> as I see it, AnalyzeRegistry has two use cases: analyzing a whole registry, in which case a couple unreachable-at-HEAD packages is somewhat expected and it's not that important to go out of our way to find their code, and for analyzing a particular package, in which case the code probably exists or else you wouldn't be looking at it.

Agreed, especially on the first use case: I don't mind missing few packages out of 4k+, in this case we're more interested in doing statistics
